# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  pulumi: pulumi/pulumi@2.0.0

jobs:
  deploy:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - pulumi/login:
          version: 3.89.0
      - run:
          name: Authenticate with GCP
          command: |
            echo $RANDOM_STRING | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: Save GCP credentials
          command: |
            echo $RANDOM_STRING > ~/gcloud-service-key.json
            echo "export GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json" >> $BASH_ENV
      - run:
          name: Install npm dependencies in the infra directory
          command: npm ci
          working_directory: ./infra
      - run:
          name: Preview pulumi changes
          command: pulumi preview -s linhvuvan2022/poc-compute-engine/dev
          working_directory: ./infra
      - run:
          name: Deploy pulumi changes
          command: |
            cat ~/gcloud-service-key.json
            pulumi refresh -s linhvuvan2022/poc-compute-engine/dev -y
            pulumi up -s linhvuvan2022/poc-compute-engine/dev -y
          working_directory: ./infra

workflows:
  pulumi-workflow:
    jobs:
      - deploy
